version: '3.8'


x-variables:
  application_profile: &application_profile prod


services:
  mysql-app-db:
    image: mysql:8.0
    container_name: mysql-app-db
    restart: always
    environment:
      MYSQL_DATABASE: sunbank
      MYSQL_USER: user
      MYSQL_PASSWORD: docker123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-app-ms-net


  configserver:
    image: codebysun/configserver:v5
    container_name: configserver
    ports:
      - "8071:8071"
    environment:
      SPRING_PROFILES_ACTIVE: git,prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8071/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - spring-app-ms-net
  
  
  eurekaserver:
    image: codebysun/eurekaserver:v5
    container_name: eurekaserver
    depends_on:
      configserver:
        condition: service_healthy
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      EUREKA_INSTANCE_HOSTNAME: eurekaserver
      SPRING_CONFIG_SERVER: http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8070/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - spring-app-ms-net

  accounts:
    image: codebysun/accounts:v5
    container_name: accounts
    depends_on:
      mysql-app-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_CONFIG_SERVER: http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    #    entrypoint: ["/bin/sh", "-c", "echo Starting Account Application  && java -jar app.jar --spring.profiles.active=*application_profile"]
    networks:
      - spring-app-ms-net

  loans:
    image: codebysun/loans:v5
    container_name: loans
    depends_on:
      mysql-app-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_CONFIG_SERVER: http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    #    entrypoint: [ "/bin/sh", "-c", "echo Starting Loan Application  && java -jar app.jar --spring.profiles.active=*application_profile" ]
    networks:
      - spring-app-ms-net

  cards:
    image: codebysun/cards:v5
    container_name: cards
    depends_on:
      mysql-app-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_CONFIG_SERVER: http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
    #    entrypoint: [ "/bin/sh", "-c", "echo Starting Card Application  && java -jar app.jar --spring.profiles.active=*application_profile" ]
    networks:
      - spring-app-ms-net

volumes:
  mysql-data:

networks:
  spring-app-ms-net:
    driver: bridge