version: '3.8'

x-variables:
  application_profile: &application_profile prod

services:
  mysql-app-db:
    image: mysql:8.0
    container_name: mysql-app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sunbank
      MYSQL_USER: user
      MYSQL_PASSWORD: docker123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sunbank-ms-net

  configserver:
    image: codebysun/configserver:v5
    container_name: configserver
    ports:
      - "8071:8071"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/prasunpatidar94/workspace-intreview
    depends_on:
      - mysql-app-db
    networks:
      - sunbank-ms-net

  eurekaserver:
    image: codebysun/eurekaserver:v5
    container_name: eurekaserver
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      EUREKA_INSTANCE_HOSTNAME: eurekaserver
    depends_on:
      - configserver
    networks:
      - sunbank-ms-net

  accounts:
    image: codebysun/accounts:v5
    container_name: accounts
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eurekaserver:8070/eureka/'
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
    depends_on:
      - mysql-app-db
      - configserver
      - eurekaserver
    networks:
      - sunbank-ms-net

  loans:
    image: codebysun/loans:v5
    container_name: loans
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eurekaserver:8070/eureka/'
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
    depends_on:
      - mysql-app-db
      - configserver
      - eurekaserver
    networks:
      - sunbank-ms-net

  cards:
    image: codebysun/cards:v5
    container_name: cards
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: *application_profile
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eurekaserver:8070/eureka/'
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
    depends_on:
      - mysql-app-db
      - configserver
      - eurekaserver
    networks:
      - sunbank-ms-net

volumes:
  mysql-data:

networks:
  sunbank-ms-net:
    driver: bridge
