version: '3.8'

services:
  mysql-app-db:
    image: mysql:8.0
    container_name: mysql-app-db
    restart: always
    environment:
      MYSQL_DATABASE: sunbank
      MYSQL_USER: user
      MYSQL_PASSWORD: docker123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-app-ms-net


  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "9000:9000"       # RabbitMQ messaging port
      - "50000:50000"     # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-app-ms-net

  configserver:
    image: codebysun/configserver:latest
    container_name: configserver
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8071:8071"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 9000
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-app-ms-net

  accounts:
    image: codebysun/accounts:latest
    container_name: accounts
    depends_on:
      mysql-app-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - spring-app-ms-net

  loans:
    image: codebysun/loans:latest
    container_name: loans
    depends_on:
      mysql-app-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - spring-app-ms-net

  cards:
    image: codebysun/cards:latest
    container_name: cards
    depends_on:
      mysql-app-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app-db:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: docker123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - spring-app-ms-net

networks:
  spring-app-ms-net:
    driver: bridge