server:
  port: 8080
spring:
  profiles:
    active: local
  application:
    name: accounts

management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0 V"

accounts:
  massage: "Welcome In SunBank ...!"
  contactDetails:
    name: "Prasun Patidar"
    email: "codebysun@gmail.com"
  onCallSupport:
    - 88888-88888
    - 99999-99999
