spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sunbank?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver

build:
  version: "Local-Release-1.0 V"

cards:
  massage: "Welcome In SunBank Cards Application with Local configuration.. Changes !"
  contactDetails:
    name: "Prasun Patidar"
    email: "{cipher}7e5f115446a084a43d93e9a9f5654f04ff14d1960ef705048348de9769d50c1e8695b0855a6797116a1f4d587685fe43"
  onCallSupport:
    - 22222-22222
    - 66666-44444
#  http://localhost:8082/actuator/refresh --post