server:
  port: 8082
spring:
  profiles:
    active: default
  application:
    name: "cards"

  datasource:
    url: jdbc:mysql://localhost:3308/cards_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: cards
    password: cards
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: "configserver:http://localhost:8071/"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always            # Options: always, embedded, never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0 V"

cards:
  massage: "Welcome In SunBank Cards Application...Local!"
  contactDetails:
    name: "Prasun Patidar"
    email: "codebysun@gmail.com"
  onCallSupport:
    - 88888-77777
    - 99999-66666
