server:
  port: ${SERVER_PORT:8070}

spring:
  config:
    import: "configserver:http://${CONFIG_SERVER_HOST:configserver}:${CONFIG_SERVER_PORT:8071}/"

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eurekaserver}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${SERVER_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
