spring:
  config:
    import: ${SPRING_CONFIG_SERVER}
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

#  server:
#    enable-self-preservation: false  # optional: disable self-preservation for dev
#    eviction-interval-timer-in-ms: 5000  # heartbeat eviction interval
