spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: ${SPRING_CONFIG_SERVER}
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}


#    import: "optional:configserver:http://localhost:8071/"
build:
  version: "Docker-Release-1.0 V"

loans:
  massage: "Welcome In SunBank Loans Application with Docker configuration..!"
  contactDetails:
    name: "Prasun Patidar"
    email: "{cipher}7e5f115446a084a43d93e9a9f5654f04ff14d1960ef705048348de9769d50c1e8695b0855a6797116a1f4d587685fe43"
  onCallSupport:
    - 11111-11111
    - 77777-77777