#server:
#  port: 8071

spring:
#  application:
#    name: configserver
#  profiles:
#    active: git,prod
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
#          force-pull: true
#          timeout: 5
#          search-paths: "/MS-Spring-Boot/Section-5_eureka_server/configserver/src/main/resources/config"
#          default-label: "main"
#          clone-on-start: true
#encrypt:
#  key: "a3f5e9c2b1d4f6e7c8a9bt3k52764tb5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1"
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      probes:
#        enabled: true
#  health:
#    liveness-state:
#      enabled: true
#    readiness-state:
#      enabled: true
