##start with base image for platfoem
#FROM openjdk:17-jdk-slim
#MAINTAINER codeBySUN.com
#COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]
