server:
  port: 8082
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
#  application:
#    name: "cards"
#  config:
#    import: "optional:configserver:http://localhost:8071/"
##  rabbitmq:
#    host: localhost
#    password: "guest"
#    username: "guest"
#    port: 9000
#  http://localhost:8082/actuator/busrefresh  --any of the service sit will refresh all services
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always            # Options: always, embedded, never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0 V"

cards:
  massage: "Welcome In SunBank Cards Application...!"
  contactDetails:
    name: "Prasun Patidar"
    email: "codebysun@gmail.com"
  onCallSupport:
    - 88888-77777
    - 99999-66666
